### ISSUE TITLE
Docs incorrectly refers to `select_many` as a field option

### ISSUE THREAD

**Issue by rudokemper** [digidem/mapeo-docs-new#16]
The Mapeo docs sometimes refers to `select_many` as a field option for selecting multiple choices. This should be `select_multiple`. 

Some examples:

* https://docs.mapeo.app/complete-reference-guide/customization-options/custom-configurations/creating-custom-configurations/coding-configuration/creating-fields
* https://docs.mapeo.app/complete-reference-guide/customization-options/custom-configurations/creating-custom-configurations/planning-configuration-and-data-structure/details-fields

**Comment by emreiser** [comment]
Thanks for the eyes on this! Just updated the custom configs section.
